export const state = {
    isLoading: false,
    access_token: '',
    countInDollars: true,
    phone: '',
    annualRate: '',
    dollarRate: '',
    prize: '',
    userData: {},
    period: '',
    product_code: '',
    calcSum: '',
    wholeCalcSumObj: '',
    intervalValue: 2,
    openSettings: false,
    usd_exchange_rate: '',
    showEmailField: false,
    documentsList: [],
    loading: {
        annualRate: false,
        usdExchangeRate: false,
        insuredSum: false,
        userName: false,
    },
}